name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/products/hoodie_sport_grey.png
    - assets/images/products/hoodie_sport_navy.png
    - assets/images/products/hoodie_sport_black.png
    - assets/images/products/hoodie_upsu_navy.png
    - assets/images/products/hoodie_upsu_black.png
    - assets/images/products/hoodie_upsu_grey.png
    - assets/images/products/hoodie_portsmouth_navy.png
    - assets/images/products/hoodie_portsmouth_burgundy.png
    - assets/images/products/tshirt_upsu_sports_black.png
    - assets/images/products/tshirt_upsu_sports_navy.png
    - assets/images/products/tshirt_upsu_sports_grey.png
    - assets/images/products/tshirt_portsmouth_full_purple.png
    - assets/images/products/tshirt_portsmouth_full_white.png
    - assets/images/products/tshirt_portsmouth_white.png
    - assets/images/products/tshirt_portsmouth_navy.png
    - assets/images/products/tshirt_portsmouth_grey.png
    - assets/images/products/accessory_cap_black.png
    - assets/images/products/accessory_cap_navy.png
    - assets/images/products/accessory_water_bottle_black.png
    - assets/images/products/accessory_backpack_black.png
    - assets/images/products/stationery_pen_set_black.png
    - assets/images/products/stationery_pen_set_navy.png
    - assets/images/products/stationery_notebook_purple.png
    - assets/images/google_logo.png
